[package]
name = "markdown-extract"
description = "Extract sections of a markdown file."
version = "1.0.0"
authors = ["Sean Bailey <hello@seanbailey.dev>"]
license = "MIT"
repository = "https://github.com/sean0x42/markdown-extract"
keywords = ["markdown", "extract"]
edition = "2018"
exclude = [".github/*"]
readme = "README.md"

[[bin]]
name = "markdown-extract"
path = "src/bin.rs"

[dependencies]
log = "0.4"
regex = "1.3"
structopt = "0.3"
