name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # e.g. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    
    - name: Install markdown-extract
      run: cargo install markdown-extract

    - name: Get tag string
      id: tag
      run: echo ::set-output name=value::${GITHUB_REF/refs\/tags\//}

    - name: Get release body
      id: release_notes
      run: |
        text=`~/.cargo/bin/markdown-extract -i ${{ steps.tag.outputs.value }} CHANGELOG.md`
        echo $text
        text="${text//'%'/'%25'}"
        text="${text//$'\n'/'%0A'}"
        text="${text//$'\r'/'%0D'}"
        echo "::set-output name=value::$text"

    - name: Create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.tags.outputs.value }}
        body: ${{ steps.release_notes.outputs.value }}
